barhop/barhop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='/bars/', permanent=False)),
    path('accounts/', include('user_management.urls', namespace="auth")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('bars/', include('bars.urls', namespace="bars")),
    path('reviews/', include('reviews.urls', namespace="reviews")),
    path('reservations/', include('reservations.urls', namespace="reservations")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barhop/bars/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.bar_list, name='bar-list'),
    path('create/', views.create_bar, name='create-bar'),
    path('user/<slug:username>/', views.bar_list, name='bar-list'),
    path('<int:bar_id>/', views.bar_details, name='bar-details'),
    path('<int:bar_id>/update', views.bar_update, name='bar-update'),
]

app_name = "bars"

barhop/user_management/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/check-username', views.check_existing_username, name='check_username'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/update/', views.update_profile, name="update_profile"),
]

app_name = "user_management"

barhop/templates/base.html
{% load static %}

<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />

    <link href="{% static 'plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/x-icon" href="{% static 'media/favicon.ico' %}" />
    <script src="{% static 'js/custom.js' %}"></script>

    <!-- Additional Stylesheets -->
    {% block styles %}{% endblock %}
    <style>
      @media (min-width: 576px) {
        main { margin-top: 75px; }
      }
      
      @media (max-width: 575px) {
        main { margin-bottom: 65px; overflow: auto; }
      }
    </style>

    <title>BarHop - {% block title %}{% endblock %}</title>
  </head>

  <body>
    <nav class="d-flex bg-gray-100 border-bottom border-top border-gray-200 px-5 px-sm-12 align-items-center justify-content-between w-100 z-index-3 position-fixed h-fit py-5">
      <!-- Left of Nav -->
      <a class="d-sm-flex d-none gap-3 h-40px align-items-center" href="/">
        <span class="fw-bolder fs-1 text-gray-900 text-hover-info" style="font-family: 'Poppins';">BarHop</span>
      </a>

      <!-- Links -->
      <div class="d-flex flex-row justify-content-around w-100 w-sm-fit fs-6 fw-semibold position-relative">
        <a class="nav-link text-hover-info px-5 py-0 py-sm-3 d-flex flex-column align-items-center w-100px w-sm-fit{% if request.path == '/bars/' %} active{% endif %}" href="/">
          <i class="ki-outline ki-home fs-2 d-sm-none"></i>
          <span class="fs-sm-6 fs-8 pt-1 p-sm-0">Home</span>
        </a>
        {% if request.user.is_authenticated and user.user_type == "OWNER" %}
          <a class="nav-link text-hover-info px-5 py-0 py-sm-3 d-flex flex-column align-items-center w-100px w-sm-fit{% if "/bars/" in request.path and request.path != '/bars/' %} active{% endif %}" href="{% url 'bars:bar-list' user.username %}">
            <i class="ki-outline ki-shop fs-2 d-sm-none"></i>
            <span class="fs-sm-6 fs-8 pt-1 p-sm-0">My Bars</span>
          </a>
        {% endif %}
        <a class="nav-link text-hover-info px-5 py-0 py-sm-3 d-flex flex-column align-items-center w-100px w-sm-fit{% if "/reservations" in request.path %} active{% endif %}" href="#">
          <i class="ki-outline ki-cheque fs-2 d-sm-none"></i>
          {% if request.user.is_authenticated and user.user_type == "OWNER" %}
            <span class="fs-sm-6 fs-8 pt-1 p-sm-0">Reservations</span>
          {% else %}
            <span class="fs-sm-6 fs-8 pt-1 p-sm-0">My Bookings</span>
          {% endif %}
        </a>
        <a class="nav-link text-hover-info px-5 py-0 py-sm-3 d-flex flex-column align-items-center w-100px w-sm-fit d-sm-none{% if "/profile" in request.path %} active{% endif %}" href="{% url 'auth:update_profile' %}">
          <i class="ki-outline ki-profile-circle fs-2"></i>
          <span class="fs-sm-6 fs-8 pt-1 p-sm-0">Profile</span>
        </a>
        <span class="nav-hover-pill d-sm-block d-none bg-info bg-opacity-15 border-info border-opacity-50 start-0 position-absolute h-100 z-index-n1 rounded-pill"></span>
      </div>

      <!-- Right of Nav -->
      <div class="d-sm-flex d-none flex-row gap-3">
        {% if request.user.is_authenticated %}
          <div class="d-flex flex-row align-items-center gap-4" data-kt-menu-trigger="{default:'click', lg:'hover'}" data-kt-menu-placement="bottom" data-kt-menu-offset="0,20">
            <div class="w-40px h-40px d-flex align-items-center justify-content-center rounded-circle bg-gray-300">
              {% if not user.profile_pic %}
                <span class="fs-2 fw-semibold text-gray-700 text-center">{{ user.username|slice:"0:1" }}</span>              
              {% endif %}
            </div>
            <div class="d-flex flex-column">
              <span class="text-gray-600 fw-semibold fs-7 text-nowrap">Welcome back,</span>
              <span class="text-gray-800 fs-6 fw-bold d-flex align-items-center text-nowrap">
                {{ user.first_name }} {{ user.last_name }}
              </span>
            </div>
            <i class="fs-1 text-gray-600 ki-solid ki-down hover-rotate-180"></i>
          </div>
          <div class="menu menu-sub menu-sub-dropdown menu-gray-700 menu-hover-primary menu-hover-bg menu-rounded fw-semibold p-3 w-150px" data-kt-menu="true">
            <div class="menu-item">
              <a href="{% url 'auth:update_profile' %}" class="menu-link">
                <span class="menu-icon">
                  <i class="ki-duotone ki-profile-circle fs-2">
                    <span class="path1"></span>
                    <span class="path2"></span>
                    <span class="path3"></span>
                    <span class="path4"></span>
                  </i>
                </span>
                <span class="menu-title">Profile</span>
              </a>
            </div>
            <div class="menu-item">
              <form method="POST" action="{% url 'logout' %}" class="d-flex m-0">
                {% csrf_token %}
                <button class="menu-link" type="submit">
                  <span class="menu-icon">
                    <i class="ki-duotone ki-exit-right fs-2">
                    <span class="path1"></span>
                    <span class="path2"></span>
                    </i>
                  </span>
                  <span class="menu-title">Logout</span>
                </button>
              </form>
            </div>
          </div>
        {% else %}
          <a href="{% url 'login' %}" class="btn btn-info btn-sm text-nowrap rounded-pill">Login</a>       
        {% endif %}
      </div>
    </nav>

    <main>
      {% block content %}{% endblock %}
    </main>
    
    <!-- Global Javascript Bundles -->
    <script src="{% static 'plugins/global/plugins.bundle.js' %}"></script>
    <script src="{% static 'js/scripts.bundle.js' %}"></script>

    <!-- Additional Javascript -->
    {% block scripts %}{% endblock %}
  </body>
</html>

barhop/templates/no-nav.html
{% load static %}

<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />

    <link href="{% static 'plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/x-icon" href="{% static 'media/favicon.ico' %}" />
    <script src="{% static 'js/custom.js' %}"></script>

    <!-- Additional Stylesheets -->
    {% block styles %}{% endblock %}
    <style>
      @media (min-width: 576px) {
        aside.auth-img {
          background-image: linear-gradient(90deg,rgba(27, 27, 41, 1) 0%, rgba(27, 27, 41, 0.6) 70%, rgba(27, 27, 41, 0.3) 100%), url("{% static 'media/drinks.webp' %}") !important;
        }
      }

      aside.auth-img {
        background-size: cover;
        background-image: linear-gradient(0deg,rgba(27, 27, 41, 1) 0%, rgba(27, 27, 41, 0.6) 70%, rgba(27, 27, 41, 0.3) 100%), url("{% static 'media/drinks.webp' %}");
      }
    </style>

    <title>BarHop - {% block title %}{% endblock %}</title>
  </head>

  <body class="d-flex flex-sm-row flex-column-reverse">
    <main class="flex-grow-1 flex-lg-grow-0 w-lg-50">
      {% block content %}

      {% endblock %}
    </main>
    <aside class="auth-img h-150px h-sm-100 flex-sm-grow-1"></aside>

    <!-- Global Javascript Bundles -->
    <script src="{% static 'plugins/global/plugins.bundle.js' %}"></script>
    <script src="{% static 'js/scripts.bundle.js' %}"></script>

    <!-- Additional Javascript -->
    {% block scripts %}{% endblock %}
  </body>
</html>